name: VERCEL Tests

on:
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Notify Slack that tests have started
      - name: Notify Slack that tests have started
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":bell: *Buurtdashboard Tests Started* :bell:"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL_ORG }}

      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
      
      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium
      - name: Set test URL
        id: set-url
        run: |
          DEPLOY_URL="${{ github.event.deployment_status.environment_url }}"
          echo "Deployment URL: $DEPLOY_URL"
          
          # Default to dev if no specific URL provided
          if [ -z "$DEPLOY_URL" ] || [ "$DEPLOY_URL" = "null" ]; then
            DEPLOY_URL="https://buurtdashboard-dev.vercel.app"
            echo "Using fallback URL: $DEPLOY_URL"
          fi
          
          echo "test_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          
      - name: Run Playwright tests
        id: test
        run: |
          echo "Running Playwright tests..."
          echo "Testing URL: ${{ steps.set-url.outputs.test_url }}"
          npx playwright test --reporter=github
        env:
          BASE_URL: ${{ steps.set-url.outputs.test_url }}
          CI: true

      - name: Capture Test Result (Failure or Success)
        id: result
        run: |
          if [ $? -ne 0 ]; then
            echo "::set-output name=test-status::failure"
          else
            echo "::set-output name=test-status::success"
          fi

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Send Slack Notification on Success
      - name: Send Slack Notification on Success
        if: steps.result.outputs.test-status == 'success'  # Send notification only if tests pass
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ORG }}  # Use GitHub secret for the Webhook URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":tada: *Buurtdashboard Tests Passed* :tada:"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL_ORG }}

      # Send Slack Notification on Failure
      - name: Send Slack Notification on Failure
        if: steps.result.outputs.test-status == 'failure'  # Send failure notification if tests failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ORG }}  # Use GitHub secret for the Webhook URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":x: *Buurtdashboard Tests Failed* :x:"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL_ORG }}

      # Send Slack Notification on Timeout (Job Cancelled)
      - name: Send Slack Notification on Timeout (Cancelled)
        if: ${{ cancelled() }}  # Triggered if the job was cancelled due to timeout
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ORG }}  # Use GitHub secret for the Webhook URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":x: *Buurtdashboard Tests Timed Out* :x:"
                }
              },
              {
                "type": "section",
                "block_id": "section-2",
                "text": {
                  "type": "mrkdwn",
                  "text": "The Playwright tests timed out after 3 minutes."
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL_ORG }}