name: VERCEL Tests

on:
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # Notify Slack that tests have started
      - name: Notify Slack that tests have started
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":bell: *Playwright Tests Started* :bell:"
                }
              },
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Send Slack Notification on Test Success
      - name: Send Slack Notification on Success
        if: success()  # Runs only if Playwright tests pass
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Use GitHub secret for the Webhook URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":tada: *Vercel Deployment and Playwright Tests Passed!* :tada:"
                }
              },
              {
                "type": "section",
                "block_id": "section-2",
                "text": {
                  "type": "mrkdwn",
                  "text": "The deployment to *${{ github.event.deployment_status.environment }}* has succeeded, and the Playwright tests have passed successfully. Everything is green! :checkered_flag:"
                }
              },
              {
                "type": "section",
                "block_id": "section-3",
                "text": {
                  "type": "mrkdwn",
                  "text": "You can view the Playwright report artifact here: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts|Playwright Report>"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      # Send Slack Notification on Failure
      - name: Send Slack Notification on Failure
        if: failure()  # Runs only if Playwright tests fail
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Use GitHub secret for the Webhook URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":x: *Vercel Deployment Succeeded, But Playwright Tests Failed* :x:"
                }
              },
              {
                "type": "section",
                "block_id": "section-2",
                "text": {
                  "type": "mrkdwn",
                  "text": "The deployment to *${{ github.event.deployment_status.environment }}* has succeeded, but the Playwright tests have failed. Please check the logs to investigate the issue."
                }
              },
              {
                "type": "section",
                "block_id": "section-3",
                "text": {
                  "type": "mrkdwn",
                  "text": "You can view the Playwright report artifact here: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts|Playwright Report>"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
