name: VERCEL Tests

on:
  deployment_status:

jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 1 # Timeout set to 3 minutes
    steps:
      # Notify Slack that tests have started
      - name: Notify Slack that tests have started
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":bell: *Playwright Tests Started* :bell:"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run Playwright tests
        id: test
        run: |
          echo "Running Playwright tests..."
          npx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Capture Timeout or Failure
        id: result
        run: |
          if [[ $GITHUB_RUN_ATTEMPT -gt 1 ]]; then
            echo "Tests timed out or failed due to job timeout."
            echo "::set-output name=test-status::timeout"
          elif [ $? -ne 0 ]; then
            echo "Tests failed."
            echo "::set-output name=test-status::failure"
          else
            echo "Tests passed."
            echo "::set-output name=test-status::success"
          fi

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Send Slack Notification on Test Success
      - name: Send Slack Notification on Success
        if: steps.result.outputs.test-status == 'success'  # Send notification only if tests pass
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Use GitHub secret for the Webhook URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "block_id": "section-1",
                "text": {
                  "type": "mrkdwn",
                  "text": ":tada: *Playwright Tests Passed* :tada:"
                }
              },
              {
                "type": "section",
                "block_id": "section-2",
                "text": {
                  "type": "mrkdwn",
                  "text": "The deployment to *${{ github.event.deployment_status.environment }}* has succeeded, and the Playwright tests passed successfully."
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      # Send Slack Notification on Failure (including timeout)
      - name: Send Slack Notification on Failure or Timeout
        if: steps.result.outputs.test-status == 'failure' || steps.result.outputs.test-status == 'timeout'  # Send notification if tests fail or timeout
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Use GitHub secret for the Webhook URL
        run: |
          if [ "${{ steps.result.outputs.test-status }}" == "timeout" ]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{
              "blocks": [
                {
                  "type": "section",
                  "block_id": "section-1",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: *Playwright Tests Timed Out* :x:"
                  }
                },
                {
                  "type": "section",
                  "block_id": "section-2",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The deployment to *${{ github.event.deployment_status.environment }}* has succeeded, but the Playwright tests timed out after 1 minutes."
                  }
                }
              ]
            }' ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            curl -X POST -H 'Content-type: application/json' \
            --data '{
              "blocks": [
                {
                  "type": "section",
                  "block_id": "section-1",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: *Playwright Tests Failed* :x:"
                  }
                },
                {
                  "type": "section",
                  "block_id": "section-2",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The deployment to *${{ github.event.deployment_status.environment }}* has succeeded, but the Playwright tests failed."
                  }
                }
              ]
            }' ${{ secrets.SLACK_WEBHOOK_URL }}
          fi